import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { analysisId } = await req.json();
    console.log('Generating report for analysis ID:', analysisId);

    const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    // Initialize Supabase client
    const supabase = createClient(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!);

    // Get the analysis data
    const { data: analysis, error: fetchError } = await supabase
      .from('symptom_analyses')
      .select('*')
      .eq('id', analysisId)
      .single();

    if (fetchError || !analysis) {
      throw new Error('Analysis not found');
    }

    if (!analysis.analysis_result) {
      throw new Error('Analysis not completed yet');
    }

    // Generate comprehensive report
    const report = {
      reportId: `RPT-${Date.now()}`,
      generatedAt: new Date().toISOString(),
      patientInfo: {
        age: analysis.patient_age || 'Not provided',
        gender: analysis.patient_gender || 'Not provided',
        weight: analysis.patient_weight || 'Not provided',
        allergies: analysis.patient_allergies || 'None reported',
        medications: analysis.patient_medications || 'None reported'
      },
      symptoms: analysis.symptoms,
      description: analysis.description || 'No additional details provided',
      analysisDate: analysis.created_at,
      aiAnalysis: analysis.analysis_result,
      confidenceScore: analysis.confidence_score,
      recommendations: {
        immediateActions: [],
        lifestyle: [],
        followUp: analysis.analysis_result.follow_up || 'Consult healthcare provider as needed'
      },
      disclaimer: "This report is generated by AI for educational purposes only. It should not replace professional medical advice, diagnosis, or treatment. Always seek the advice of qualified health providers with any questions you may have regarding a medical condition."
    };

    // Add immediate actions based on severity
    if (analysis.analysis_result.severity_overall === 'severe' || analysis.analysis_result.seek_immediate_care) {
      report.recommendations.immediateActions.push('Seek immediate medical attention');
      report.recommendations.immediateActions.push('Do not delay professional medical consultation');
    } else if (analysis.analysis_result.severity_overall === 'moderate') {
      report.recommendations.immediateActions.push('Schedule appointment with healthcare provider within 1-2 days');
    } else {
      report.recommendations.immediateActions.push('Monitor symptoms and seek care if they worsen');
    }

    // Add lifestyle recommendations
    report.recommendations.lifestyle = analysis.analysis_result.care_recommendations || [];

    console.log('Report generated successfully for analysis ID:', analysisId);

    return new Response(JSON.stringify({ 
      success: true, 
      report: report 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in generate-report function:', error);
    return new Response(JSON.stringify({ 
      error: error.message || 'Failed to generate report' 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});