// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojcqsexcmzkisexruhde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qY3FzZXhjbXpraXNleHJ1aGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTc2NTcsImV4cCI6MjA3MTkzMzY1N30.u00hPI-IbW2Y4d5Opq_csBrWxSbJANtT91rO0r_H4gE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});